name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Build Docker image
        run: docker build -t sasideva/node .

      
      - name: Run Docker container
        run: docker run -d --rm --name test_container sasideva/node

    
      - name: Run tests
        run: docker exec test_container npm test  

      
      - name: Stop and remove Docker container
        if: always()
        run: |
          docker stop test_container || true
          docker rm test_container || true
