name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub (you'll need to set DOCKER_USERNAME and DOCKER_PASSWORD as repository secrets in GitHub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t sasideva/node .

      # Step 4: Run the Docker container
      - name: Run Docker container
        run: docker run -d --rm --name test_container sasideva/node

      # Step 5: Run tests or commands inside the Docker container
      - name: Run tests
        run: docker exec test_container npm test  # Replace with your test command if necessary

      
      - name: Stop and remove Docker container
        if: always()
        run: |
          docker stop test_container || true
          docker rm test_container || true
