name: CICD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .  
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/node:latest 

      - name: Log out from Docker Hub
        run: docker logout

      - name: Notify Success
        if: success()
        run: echo "Docker image has been built and pushed successfully!"

      - name: Add SSH key for EC2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          ssh -i ec2_key.pem -o "StrictHostKeyChecking=no" ec2-13-48-42-228.eu-north-1.compute.amazonaws.com << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/node:latest
            docker stop node || true
            docker rm node || true
            docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/node:latest
          EOF

